import QtQuick

ListModel {
    id: wordList

    ListElement { word: "MAUS"}
    ListElement { word: "ORT" }
    ListElement { word: "OPERATIONSVERSTAERKER" }
    ListElement { word: "BUEGELBRETT" }
    ListElement { word: "APFEL" }
    ListElement { word: "AUTO" }
    ListElement { word: "BALL" }
    ListElement { word: "BANK" }
    ListElement { word: "BAUM" }
    ListElement { word: "BIER" }
    ListElement { word: "BUCH" }
    ListElement { word: "BUS" }
    ListElement { word: "COMPUTER" }
    ListElement { word: "DACH" }
    ListElement { word: "DORF" }
    ListElement { word: "EISBAER" }
    ListElement { word: "FENSTER" }
    ListElement { word: "FISCH" }
    ListElement { word: "FLUGZEUG" }
    ListElement { word: "FREUND" }
    ListElement { word: "GARTEN" }
    ListElement { word: "GELD" }
    ListElement { word: "HAUS" }
    ListElement { word: "HUND" }
    ListElement { word: "IDEE" }
    ListElement { word: "JACKE" }
    ListElement { word: "JAHR" }
    ListElement { word: "JUNGE" }
    ListElement { word: "KATZE" }
    ListElement { word: "KIND" }
    ListElement { word: "KIRCHE" }
    ListElement { word: "KOFFFER" }
    ListElement { word: "KUEHLSCHRANK" }
    ListElement { word: "LAMPE" }
    ListElement { word: "LEHRER" }
    ListElement { word: "LICHT" }
    ListElement { word: "MARKT" }
    ListElement { word: "MUTTER" }
    ListElement { word: "NACHT" }
    ListElement { word: "NASE" }
    ListElement { word: "PAPIER" }
    ListElement { word: "PARK" }
    ListElement { word: "PFLANZE" }
    ListElement { word: "SCHULE" }
    ListElement { word: "SONNE" }
    ListElement { word: "STADT" }
    ListElement { word: "STUHL" }
    ListElement { word: "TISCH" }
    ListElement { word: "TOMATE" }
    ListElement { word: "UHR" }
    ListElement { word: "VOGEL" }
    ListElement { word: "WASSER" }
    ListElement { word: "WEG" }
    ListElement { word: "WORT" }
    ListElement { word: "ZIMMER" }
    ListElement { word: "AUTO" }
    ListElement { word: "BAECKEREI" }
    ListElement { word: "BETT" }
    ListElement { word: "BRIEF" }
    ListElement { word: "COLA" }
    ListElement { word: "COMPUTER" }
    ListElement { word: "FERNSEHEN" }
    ListElement { word: "FLASCHE" }
    ListElement { word: "FREUNDSCHAFT" }
    ListElement { word: "GARBE" }
    ListElement { word: "GAST" }
    ListElement { word: "GESCHIRR" }
    ListElement { word: "GEBURTSTAG" }
    ListElement { word: "GLAESER" }
    ListElement { word: "GRAS" }
    ListElement { word: "HANDTUCH" }
    ListElement { word: "HAUSAUFGABE" }
    ListElement { word: "HERD" }
    ListElement { word: "KARTE" }
    ListElement { word: "KIRSCHE" }
    ListElement { word: "KOMPASS" }
    ListElement { word: "KUEHLSCHRANK" }
    ListElement { word: "LIEBE" }
    ListElement { word: "MUETZE" }
    ListElement { word: "NOTE" }
    ListElement { word: "OBST" }
    ListElement { word: "OFEN" }
    ListElement { word: "POLIZEI" }
    ListElement { word: "POST" }
    ListElement { word: "QUITTUNG" }
    ListElement { word: "RECHNUNG" }
    ListElement { word: "SESSSEL" }
    ListElement { word: "SCHLUESSEL" }
    ListElement { word: "SPIEGEL" }
    ListElement { word: "STADTPLAN" }
    ListElement { word: "SUPPE" }
    ListElement { word: "TASSE" }
    ListElement { word: "TEEKANNE" }
    ListElement { word: "TUER" }
    ListElement { word: "WASSERKOCHER" }
    ListElement { word: "WETTER" }
    ListElement { word: "WIESE" }
    ListElement { word: "WERKSTATT" }
    ListElement { word: "ZELT" }
    ListElement { word: "ZIRKUS" }
    ListElement { word: "ZAHNARZT" }
    ListElement { word: "ZUG" }
    ListElement { word: "SCHLUESSEL" }
    ListElement { word: "ZUCKERTUETE" }
}

